### ISSUE TITLE
Consider adding `Eq`

### ISSUE THREAD

**Issue by ctron** [idubrov/json-patch#15]
The types `Patch`, `PatchOperation`, and all of their used types are marked as `PartialEq` only. Although all used types (like `Value`) also do support `Eq`.

I think it would be great add `Eq` as well, so that people using `Patch`, can go for `Eq` in their own data-structures too.

I can create a PR if you like.

**Comment by idubrov** [comment]
Done in 0.2.7. Apologies for ignoring it for so long.
