### ISSUE TITLE
error[E0554]: #![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by harindaka** [idubrov/json-patch#2]
I get the following error when running `cargo build` after adding the json-patch dependency to the Cargo.toml file

error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/harindaka/.cargo/registry/src/github.com-1ecc6299db9ec823/json-patch-0.2.0/src/lib.rs:84:1
   |
84 | #![feature(test)]
   | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `json-patch`.

What can I do to make it work with Rust stable? Wouldn't being unable to compile with stable be detrimental to the adoption of this awesome library?

**Comment by idubrov** [comment]
Should be fixed in version `0.2.1`. Let me know if it doesn't.
