### ISSUE TITLE
treediff-rs dependency

### ISSUE THREAD

**Issue by zeha** [idubrov/json-patch#30]
Please see https://github.com/Byron/treediff-rs/issues/11. Apparently treediff-rs is in maintenance mode, quoting the maintainer:

> It looks like the main consumer of this library is [json-patch](https://crates.io/crates/json-patch), and I suggest to open an issue them so they contribute a fix, take over this crate, or cut the dependency to this crate in some other way.

**Comment by idubrov** [comment]
That dependency is gone now! See #37 and #38.
