### ISSUE TITLE
Breaking api change between minor versions

### ISSUE THREAD

**Issue by avtrujillo** [idubrov/json-patch#39]
The v1.3.0 release changed the type of a number of public fields in public structs to use Pointer instead of String. This caused my docker builds to start failing with errors that didn't show up when compiling outside of docker, since I had v1.2.0 cached locally. Please consider either reversing this change or bumping the major version

**Comment by pgerber** [comment]
Yanking the release and postponing the release of any breaking changes until v2 seems most reasonable option to me.

**Comment by idubrov** [comment]
Ouch. I had some breaking changes in `main`. 

Okay, I re-released the fix on top of the 1.2.0 as 1.4.0 and yanked 1.3.0. Let me know if it works!

**Comment by pepoviola** [comment]
> Ouch. I had some breaking changes in `main`.
> 
> Okay, I re-released the fix on top of the 1.2.0 as 1.4.0 and yanked 1.3.0. Let me know if it works!

Works as expected, thanks!!
