### ISSUE TITLE
add wildcard for replace array object

### ISSUE THREAD

**Issue by vovacooper** [idubrov/json-patch#42]
in case of an array object i want to be able to change all instances in all the array elements. 

#[macro_use]
use json_patch::{Patch, patch};
use serde_json::{from_value, json};

let mut doc = json!([
    { "name": "Andrew" , "123": 123},
    { "name": "Maxim", "asd": "asd" }
]);

let p: Patch = from_value(json!([
  { "op": "replace", "path": "/?/name", "value": "aaa" },
])).unwrap();

patch(&mut doc, &p).unwrap();
assert_eq!(doc, json!([
  { "name": "aaa", "123": 123 },
  { "name": "aaa" , "asd": "asd"}
]));

**Comment by idubrov** [comment]
I'm following [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902), and there are no wildcards specified there.
