### ISSUE TITLE
Revert Patch

### ISSUE THREAD

**Issue by elichai** [idubrov/json-patch#7]
Hey, 
Is there a way to revert a Patch?
e.g:
```
fn test(doc: mut Value, p: Patch) {
	let original = doc.clone();
	json_patch::patch(&mut doc, &p).unwrap();
	json_patch::revert(&mut doc, &p).unwrap();

	assert_eq(doc, original);
} 
```

**Comment by idubrov** [comment]
No, there is no way to revert a patch as some of the operations are not reversible (for example, when deleting, we don't know what was deleted).
